env:
  es2021: true
  node: true
extends: google
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
    indent: ['error', 4],
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'prefer-const': 'error',
    'no-var': 'error',
    'max-len': ['error', { code: 120 }],
    'linebreak-style': ['error', 'unix'],
    'newline-per-chained-call': ['error', {
        ignoreChainWithDepth: 2
    }]
}
