GET http://localhost:3000/users

### 
POST  http://localhost:3000/users
Content-Type: application/json

{
  "name": "user",
  "email": "asdfgh@gmail.com",
  "password": "Password",
  "confirmPassword": "Password",
  "address": "bandung",
  "birthDate": "2022-02-22"
}